### ISSUE TITLE
Gradle fetching  problem

### ISSUE THREAD

**Issue by emanuelet** [PhilJay/ValueBar#3]
Hi,
first of all thank you for the library. Is very handy and I'm using it successfully in my app.

Recently I tried to switch though  from the jar included in /libs to the gradle dependency fetched from jitpack.io but I get the following error:

```
Error:Could not find ValueBar.jar (com.github.PhilJay:ValueBar:v1.0.2).
Searched in the following locations:
    https://jitpack.io/com/github/PhilJay/ValueBar/v1.0.2/ValueBar-v1.0.2.jar
```

Could there be a naming problem with the jar file? 

That's the error that jitpack returns.
Log https://jitpack.io/com/github/PhilJay/ValueBar/v1.0.2/build.log

**Comment by jitpack-io** [comment]
Hi @emanuelet 
There wasn't a build file in the repo so JitPack couldn't build it. We just released a new feature that builds Android projects even without a build file:)
The library is there now: https://jitpack.io/com/github/PhilJay/ValueBar/v1.0.2/ValueBar-v1.0.2.pom

**Comment by mitenko** [comment]
This error is still occurring.

**Comment by jitpack-io** [comment]
@mitenko What about now?

**Comment by mitenko** [comment]
Looks like it's working. Thanks!

**Comment by ankitbatra11** [comment]
Does not work for me. Throws this error:
Error:Module 'com.github.PhilJay:ValueBar:v1.0.2' depends on one or more Android Libraries but is a jar

**Comment by laf83** [comment]
for, me adding @jar made it works.
So import become: compile 'com.github.PhilJay:ValueBar:v1.0.2@jar'
Tryed also with @aar, but give me conflicts with com.android.support:support-v4:25.xxxxx library (i think that library import an older version of support lib)
